name: automation-labels

on: pull_request_target
#  pull_request:
#    types: [opened]

jobs:
  automate-labels:
    concurrency: 
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Check organization
        id: is_organization_member
        if: github.event.action == 'opened'
        uses: OperationsYU/is-organization-member@master
        with:
          organization: OperationsYU
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Echo username organization
        run: |
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ steps.is_organization_member.outputs.result }}

      - name: Add contribution label
        if: |
          steps.is_organization_member.outputs.result == 'false'
        uses: OperationsYU/labeler@master
        with:
          add-labels: "contribution"
          run: echo User Does Not Belong to Organization

      - name: assignment
        uses: OperationsYU/auto-assignment@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          users: '["fish0607"]'
